spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/littera
spring.datasource.username=postgres
spring.datasource.password=lucas

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
